### ISSUE TITLE
Nested jar rewrite related tasks

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#36135]
We have a number of issues with the existing code and it feels like a rewrite might now be required.

The primary issues are:
- [x] #37668
- [x] #37669
- [x] #28837
- [x] #7161
- [x] #37667
- [x] #37452

Other related items:
- [x] Drop Java 8 specific code and work-arounds
- [x] Solve Windows file lock issues
- [x] <del>See if we can drop custom String code</del> (we can't)
- [x] See if we have opportunities to improve performance
- [x] See if we can address URL concerns listed in [this Jetty issue](https://github.com/eclipse/jetty.project/issues/9973#issuecomment-1613062201)
