### ISSUE TITLE
Add CloudFoundry EndpointHandlerMapping

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#7108]
We need a variant of `EndpointHandlerMapping` that exposes actuator endpoints for Cloud Foundry to use.

The endpoints should be exposed under `/cloudfoundryapplication` and should be present regardless of user endpoint settings. In addition the mapping must handle security.
# Tasks
- [x] Add new endpoint handler mapping
- [x] Add HAL like endpoint for discoverability
- [ ] Add CF security
  - [x] Extract UAA url from CC's /info
  - [x] Validate UAA token - get public keys from /token_keys, validate signature, issuer and expiry
  - [ ] Validate UAA token - validateAudience
  - [ ](Optional) Cache response to save multiple calls 
- [x] Make HealthMvcEndpoint show full details when accessed via `/cloudfoundryapplication`
- [x] Enable by default
- [x] Limit HAL based on ROLE
