### ISSUE TITLE
Rework configuration properties support

### ISSUE THREAD

**Issue by philwebb** [spring-projects/spring-boot#9000]
This bug groups the various issues that we want to fix when we rework configuration property support:

__Main issues:__
- [ ] Refine SpringApplication get/set sources (#8910)
- [ ] Restructure Origin support (#9001)
- [ ] Create new ConfigurationPropertySource abstraction (#4910)
- [ ] Add failure analysis for BindException other than BindValidationException (#8934)
- [ ] Remove relaxed attribute from @ConditionalOnProperty (#9003)

__Fixed along the way:__
- [ ] Placeholder expansion doesn't support relaxed names (#2496)
- [ ] Binding does not auto-grow arrays in Maps (#3789)
- [ ] Info Actuator Not "Relaxing" Environment Variable Sources (#7388)
- [ ] List values do not override defaults if not comma-separated (#7015)
- [ ] Fail hard on missing placeholders in configuration files (#8693)
- [ ] YAML lists cannot be mapped to Sets (#1415)
